name: basics-cdss
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipykernel
  - pyyaml
  - tqdm
  - statsmodels
  - pip:
      - pydantic>=2
      - rich
      - pytest
